# import datetime

# from bw_simapro_csv import SimaProCSV
# from bw_simapro_csv.blocks import Process


# def test_process_metadata(fixtures_dir):
#     obj = SimaProCSV(fixtures_dir / "process.csv")
#     processes = [elem.parsed for elem in obj.blocks if isinstance(elem, Process)]
#     assert len(processes) == 1
#     expected = {
#         "Allocation rules": "text for allocation rules",
#         "Boundary with nature": "Agricultural production is part of production system",
#         "Capital goods": "First order (only primary flows)",
#         "Category type": "material",
#         "Collection method": "text for collection method",
#         "Comment": "text for comment",
#         "Cut off rules": "Less than 1% (physical criteria)",
#         "Data treatment": "text for data treatment",
#         "Date": datetime.date(2014, 2, 24),
#         "Generator": "generated by: [System]",
#         "Geography": "Mixed data",
#         "Infrastructure": False,
#         "Literature references": [
#             {"reference": "Ecoinvent 3", "comment": "is copyright protected: false"}
#         ],
#         "Multiple output allocation": "Physical causality",
#         "PlatformId": "298f6b5c-46f5-11ec-81d3-0242ac130003",
#         "Process identifier": "DefaultX25250700002",
#         "Process name": "Test process",
#         "Record": "data entry by: [System]",
#         "Representativeness": "Theoretical calculation",
#         "Status": "Draft",
#         "Substitution allocation": "Actual substitution",
#         "System description": "U.S. LCI Database ⧺ system description comment",
#         "Technology": "Worst case",
#         "Time period": "2005-2009",
#         "Type": "Unit process",
#         "Verification": "text for verification",
#     }
#     assert processes[0]["metadata"] == expected
